name: run script file

on: 
  push

jobs:
  run_script_file:
    runs-on: ubuntu-latest
    steps:
      - name: run script file
        run: |
          cd https://github.com/rkrupesh44/test_gitaction/edit/main/.github/workflows
          chmod 777 scriptcall.sh
          ./scriptcall.sh
        shell: bash
  
