name: run script file

on: 
  push

jobs:
  run_script_file:
    runs-on: ubuntu-latest
    steps:
      - name: run script file
        run: |
          chmod +x scriptcall.sh
          ./scriptcall.sh
        shell: bash
  
